[package]
name = "FerumSTD"
version = "0.1.0"
upgrade_policy = "compatible"
license = "Apache-2.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
ferum_std="0x33a6417b3846f094782adb6de9c0f6256c70502bf85e483d53140be0ff87a6fd"
